# Generated by Django 3.0.3 on 2020-06-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200521_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='activepassengers',
            name='inBus',
            field=models.BooleanField(default=False),
        ),
    ]
