# Generated by Django 3.0.3 on 2020-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_activepassengers_inbus'),
    ]

    operations = [
        migrations.AddField(
            model_name='activepassengers',
            name='idDriver',
            field=models.CharField(default='z2', max_length=4),
        ),
    ]
