# Generated by Django 3.0.3 on 2020-06-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20200609_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activepassengers',
            name='idDriver',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
