# Generated by Django 3.0.3 on 2020-06-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20200609_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activepassengers',
            name='inBus',
        ),
        migrations.AlterField(
            model_name='activepassengers',
            name='idDriver',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
